// // Import necessary modules
// import { combineReducers } from "@reduxjs/toolkit";
// import { apiSlice } from './slices/apiSlice';
// import authReducer from "./slices/authSlice"

// // The root reducer includes 'auth' and other reducers generated by 'generalReducers'
// const rootReducer = combineReducers({
//   auth:authReducer,
//   api:apiSlice
// });

// export default rootReducer;
